### PR TITLE
add writing your own kata guide to repo

### PR DESCRIPTION
**Pull request by mcelearr**

### CODE REVIEW

**Comment by sofer** [comment]
@mcelearr this is amazing! I think it's ready for somebody to merge (anyone want to give it a go?).

**Comment by mcelearr** [comment]
There are actually a few things I could use help with to improve it, particularly on formatting. I'm thinking of opening some issues to see if someone with more markdown skills could address specific points but I was waiting until it's merged.

But now I think of it, maybe it's better to make those changes in the branch. What's the correct procedure?

**Comment by daymos** [comment]
Im happy to help you on this, although my markdown skill are not too great. What specific points had you in mind?

**Comment by mcelearr** [comment]
Go ahead and merge the pull request and I'll post my points as an issue.

**Comment by daymos** [comment]
ok

**Pull request merged**
