### PR TITLE
renamed folders for correct order and better overview

### PR DESCRIPTION
**Pull request by cshg**

### CODE REVIEW

**Comment by coudrew** [comment]
this looks pretty good, but the links in SUMMARY.md have to be updated. Last time I tried that there were huge conflicts, you want to give it a go @chrizzzer ?

**Comment by cshg** [comment]
@coudrew alright, I'll give it a shot. hope it works.

**Comment by cshg** [comment]
@coudrew seems to be fine now with the corrected links and no conflicts so far. feel free to check.

**Comment by cshg** [comment]
closing this one, since in my opinion the folder structure is fine so far and the small changes would just bring a lot of debugging effort regarding link fixes with it.

**Pull request closed without merging**
