### PR TITLE
Git basics

### PR DESCRIPTION
**Pull request by gabrielperales**
This is a _cheat sheet_ about git, I have to keep adding things. I will appreciate If somebody can help me adding things.

### CODE REVIEW

**Comment by daymos** [comment]
do you still need help?

**Comment by gabrielperales** [comment]
Yes, this is only a draft of what we have to do to have a good README

**Comment by daymos** [comment]
Ok so I would like to contribute to this one. Now you have added the most important commands. Should I write something about workflow? Or what do you suggest?

**Comment by gabrielperales** [comment]
We can add a small how-to about install git, and add some screenshots... and Yes, something about workflow could be very good as well.

But we should keep this file tiny...  so we can remove things if you think it is needed

**Comment by daymos** [comment]
I agree to keep it short. I'll work on installing and workflow. Regarding Images, I only have a mac, if we want screenshot for windows and linux we need to ask somebody else

**Comment by RichAWarren** [comment]
I'm on windows for the time being, let me know if you need screenshots!

**Pull request merged**
