### PR TITLE
Contribution workflow/enhance

### PR DESCRIPTION
**Pull request by ozym11**
Hey Sam,

One more edit for you to consider: the naming convention as detailed in contribution-workflow.md may present a conflict insofar as working with subdirectories within READMEs. 

The examples don't specify a workaround, but to avoid inspiring something like "README/programmer-skills/git-basics/add/intro-added" I've proposed changing the directory to the specific subdirectory before proceeding between updating the local repository and creating a new branch. 

There's probably a better way of doing this, but this was how I figured it out to commit changes within a subdirectory.

best,
R

Note: There's one commit for "html-css/choosing-a-css-framework.md" that I did not intend to include in this pull request. there's already an existing and separate pull request for that particular commit, but i have not yet figured out how to remove it from the contribution-workflow.md commit proposed above.

### CODE REVIEW

**Comment by g-sam** [comment]
I'm not sure I've understood the issue (it's been a while now since I last used git so maybe I'm not remembering it that well). Why would you end up specifying the subdirectory in the branch name? Could you restate the problem?

By the way, I don't think the instructions about how to use git in the contrib-workflow are correct. I submitted a pull request ages ago about this, but it seems to have slipped below the radar. I'm guessing maybe if you had followed the instructions proposed in that PR you wouldn't have ended up appending the extra commits to this PR. I will reassign it to you and you can see if it solves the issue.

**Comment by ozym11** [comment]
@g-sam hey,

the issue is that the naming convention for creating a new branch uses forward slash to distinguish between "file name"/ "type of change" / "short summary of change"

Notice that none of the examples provided deal with files within Subdirectories. All of these examples reference files (some of which no longer exist in the current repository) that are supposed to all reside within READMEs - **and not a child of the README directory.** 

>  Examples for possible branch names:
> - README/add/intro-added
> - ES6/correct/typos
> - ES6/correct/typos
> - hoisting/enhance/structure-changed
> - contribution-workflow/new

So, someone reading this as I was the other day may not understand immediately how he should name branches that are **within subdirectories**. Would the branches end up looking like

> **"READMEs/programmer-skills/git-basics/add/intro-added"**   ? 

Is that even valid? Or would this simply create a branch where 

```
<file name> = READMEs
<type of change> = programmer-skills
<short summary of change> = git-basics(/add/intro-added..?)
```

My suggestion as above is to simply change the directory after 

```
$git pull -u origin master
```

to eliminate any confusion about this. If i've $cd'd to the appropriate subdirectory, it isn't neccessary for me to introduce any additional forward slash in the file path. 

Alternatively, the examples can be updated to include something with a subdirectory, with an elaboratory note to explain what is going on there.

Hope that makes sense.

**Comment by g-sam** [comment]
Thanks for the clarification. IF I've understood correctly you are thinking that the branch name needs to specify the filepath in order for the right files to be included. But the branch name is just a label -- you can set it to whatever you like and edit files anywhere in the repository within that branch. So you can always start it with the filename (or anything else) without worrying what directory the file you are editing is in, or what directory you are in when you create the branch. The moment you do need to specify the filepath is when using `git add <the file path>`. There it may indeed help to have cd'ed into the directory before executing the command. You `add` the specific files whose changes you want comitted to the branch (or just add them all with `git add .`).  But, again, the filepath you specify for `add` has nothing to do with the branch name. Does this make sense? Does it address the issue you were worried about? Sorry if this is all terribly obvious and I'm still missing the point. If this does address the issue, maybe there's a one sentence clarification to be added that will stop other people getting stuck on the same point.

**Comment by ozym11** [comment]
> So you can always start it with the filename (or anything else) without worrying what directory the file you are editing is in, or what directory you are in when you create the branch. The moment you do need to specify the filepath is when using git add <the file path>.

yep, this is what I was looking for. I'll make the necessary changes.

best,

**Comment by ozym11** [comment]
@g-sam,

i've removed the original addition and replaced it with a note under the "$git add <name of the file>" step:

> _NOTE: If you are editing a file in one of "READMEs" subdirectories (e.g. "Javascript", "codewars", etc), include the file path in <name of the file>, in the above step._

**Comment by g-sam** [comment]
Great! happy to merge this, but there also commits for a different readme attached. I can't selectively merge the relevant commit (as far as I know) so could you maybe submit a PR with just the relevant edit? cheers.

**Comment by ozym11** [comment]
Hey,

The changes for the second readme have already been merged:

https://github.com/codingforeveryone/READMEs/pull/178#event-671256063

Consequently, I wouldn't worry about it appearing in the merge here.

best,

**Pull request merged**
