### PR TITLE
Solving the missing authors problem

### PR DESCRIPTION
**Pull request by g-sam**
As the contributors on several of the files were deleted, for the purposes of correctly assigning pull requests, I have trawled through the history and attempted to discover who first authored each readme. As you can see, I failed to find the author in a couple of places and I probably made some mistakes in others, so it would be great if anyone who sees this can check that their own attribution is correct and amend as necessary. Thanks!

### CODE REVIEW

**Comment by TroyMaeder** [comment]
Hi @g-sam, it looks like one of my READMEs is not on your list. The one missing is named scope-and-hoisting.md and also shortcuts.md is my README which it looks like you've assigned as unknown. Would you like me to go ahead and amend these fixes?

**Comment by g-sam** [comment]
Yes, please do amend. Thanks!

**Comment by g-sam** [comment]
@matthewglover alerted me to the fact you can quite easily find the authors with the blame button. Maybe this PR should be deleted?

**Comment by bradreeder** [comment]
Either way the blame button should probably be made public knowledge in the appropriate section. I don't see how it could hurt to commit this change but would wait to hear what others say.

**Pull request closed without merging**
