### PR TITLE
Update string-dissection-and-manipulation.md

### PR DESCRIPTION
**Pull request by msachi**
Adding eval() method for converting strings to expressions, and links to References section

### CODE REVIEW

**Comment by msachi** [comment]
@g-sam Wasn't sure who the author of this is - but you're quite active on here : )

**Comment by g-sam** [comment]
Nice work. Would also be cool if you could explain a bit more what the 'usefulness' of eval is, since you also seem to say it should never be used (which makes it use-less?!). By the way, you can get the original authors from the doc I submitted as pull request #131.

**Comment by msachi** [comment]
Hey, thanks for the feedback! Ok let's see... I didn't want to say it should never be used, but based on what I read it can be 'dangerous' to use it so you have to know what you're doing. It allowed me to solve an otherwise tricky kata very easily. Is it specifically the sentence 'You should not use `eval()` to evaluate an arithmetic expression, which JavaScript does automatically' that is confusing? What I was trying to say is that you shouldn't use `eval (2x + 3)` as you can just use `2x + 3`. However if the expression is a string `'2x + 3'` then you do have to use `eval`. I can try to make that clearer, but do let me know if it was something else that was confusing!

**Comment by msachi** [comment]
Also thanks for linking the list of authors!

**Comment by g-sam** [comment]
Yeah that sentence could probably be clearer, but I mainly meant to say it would be interesting to know more about what situations would merit running the risks of using eval.

**Pull request merged**
