### PR TITLE
Creating new README: Codewars platform

### PR DESCRIPTION
**Pull request by msachi**
Creating new README: Codewars platform

### CODE REVIEW

**Comment by san00** [comment]
Hiya, it's a good overview and explanation of codewars, perhaps you could mention something about adding your own test cases to kata and what effect having unfinished kata has on rankings etc, if any.

Apart from that, all good so far 👍

**Comment by Cleop** [comment]
Hey msachi, you might just want to make a couple of changes in this para: 

When learning a new programming language, return to old completed Katas and (if a Kata translation for that language exists), complete it again with your new language. You may find problem solving in one language is much harder than in another, and **vice** versa, so use this approach to help understand the strengths and weaknesses of your new language.

I've just moved the bracket and changed your spelling of vice versa :-)

**Comment by alwinsol** [comment]
I'm OK with this now and think its fine to merge, anyone else agree?

**Comment by msachi** [comment]
I've just fixed the typos highlighted by @Cleop

**Comment by san00** [comment]
Hiya msachi, 
in the tips for developing skills section, you might want to change this part of the sentence from Plan a training session. Consider starting with a high level Kata (7/8kyu) to warm up the brain cells.

To -  Consider starting with a level (7/8kyu)  Kata to warm up the brain cells, as these are easier than the tougher kata from level 6 onwards.

I think the term higher level could cause some confusion. :)

**Comment by marisid** [comment]
Hi msachi, 

Many thanks for your effort to put together a summary of how the codewars platform works. Great job! A couple of points to consider:
- Before diving straight into solving katas, it would be maybe better to expand a bit more on what katas are in the introduction section. This would enable even the first time users to follow the readme more easily. For example, you could say _The codewars platform offers code challenges which are called katas and can be solved using different programming languages. Warriors can get involved with the katas in a number of ways: they can solve, create, comment or review any of the katas based on a set of rules, as discussed below._
- At line 23 where you talk about searching for a kata, it would be useful to say ..._search for kata (through the 'kata' section on the left navigation bar)_... . I remember some people on the gitter channel, when they first started, asking about how you can search for different katas. 

Thanks again and I hope my feedback is constructive:)

**Comment by msachi** [comment]
Thanks @marisid , updated accordingly!

**Comment by LucyMac** [comment]
Hi @msachi, as a complete beginner in Codewars I had to read the sentence about the Kata ranking/kyus twice as I understood the word 'lowest' as implying 'lowest number'. Could you maybe simplify the sentence by omitting the words lowest/highest? 
Maybe it could also be more explicit about the words 'kyu' and 'rank' being interchangeable?
For example:

**'kyu'** ranks so far implemented, from the easiest to the hardest are as follows - **note the numbers are descending so the lowest number is the hardest level:**

Just a thought - otherwise I think it's great and all makes sense. Thanks a lot!

**Pull request merged**
