### PR TITLE
Update JavaScript-Scope.md

### PR DESCRIPTION
**Pull request by g-sam**

### CODE REVIEW

**Comment by bradreeder** [comment]
I'm not the main author but I don't mind handling this.

There are a few grammar mistakes in your edit. Line 32 it should be 'its own unique environment' instead of 'it's'. Same thing on line 71 'has its own scope.'

You use a back-tick on const and let so it might make sense to also back-tick the var keyword on line 28 and the if keyword on line 71, but I will leave that to your judgement.

**Comment by bradreeder** [comment]
Just made the edits. Let me know if you're happy and I can merge.

**Comment by g-sam** [comment]
I was following the principle of 'assign to the most recent contributor' (as per the Gitter chat, since the history has been erased). Are you able to tell who the original contributor was? 
Looks like you were the most recent in a lot of cases, as I think you moved the files around, so let me know if you're getting too many assignments!

**Comment by g-sam** [comment]
And merge away - thanks!

**Comment by bradreeder** [comment]
It's no problem to me as I need the github practice. :)

Great, merged.

**Pull request merged**
